version: 29

permalink: pretty
highlighter: none

exclude:
  - README.md
  - LICENSE
  - gulpfile.js
  - package.json
  - tmp
  - node_modules
  - css-src
  - js-src
  - _web-dev-1/README.md
  - _web-dev-1/LICENSE
  - _web-dev-2/README.md
  - _web-dev-2/LICENSE
  - _web-dev-3/README.md
  - _web-dev-3/LICENSE
  - _web-dev-4/README.md
  - _web-dev-4/LICENSE

data_dir: ./topics/_table-of-contents

collections:
  web-dev-1:
    output: true
    permalink: /courses/web-dev-1/:path/
    title: "Web Dev 1"
  web-dev-2:
    output: true
    permalink: /courses/web-dev-2/:path/
    title: "Web Dev 2"
  web-dev-3:
    output: true
    permalink: /courses/web-dev-3/:path/
    title: "Web Dev 3"
  web-dev-4:
    output: true
    permalink: /courses/web-dev-4/:path/
    title: "Web Dev 4"
  web-dev-5:
    title: "Web Dev 5"
    desc: "Applies all the previous web development knowledge to develop a fully interactive portfolio website—launched live on a custom domain. Related topics like writing for the web, search engine optimization and metadata, and repeatable web layouts are explored."
  web-dev-6:
    title: "Web Dev 6"
    desc: "Uses team projects to explore rich and creative web experiences with the focus on conceptualizing and building excellent interactive works by combining all the acquired knowledge and experience throughout the program."

kramdown:
  input: GFM

defaults:
  - scope:
      path: "topics"
    values:
      layout: article
  - scope:
      path: "courses"
    values:
      layout: week

########################################
# WEBSITE SPECIFIC CONFIG
########################################

max_weeks: 15

next_week:
  title: "Preview next week"
  submit: "Get a jump on things."
  type: next
  card_class: "card--subtle"
