version: 38

permalink: pretty
highlighter: none

exclude:
  - README.md
  - LICENSE
  - gulpfile.js
  - package.json
  - tmp
  - node_modules
  - css-src
  - js-src
  - images-embed
  - _web-dev-1/README.md
  - _web-dev-1/LICENSE
  - _web-dev-2/README.md
  - _web-dev-2/LICENSE
  - _web-dev-3/README.md
  - _web-dev-3/LICENSE
  - _web-dev-4/README.md
  - _web-dev-4/LICENSE
  - _web-dev-5/README.md
  - _web-dev-5/LICENSE
  - _web-dev-6/README.md
  - _web-dev-6/LICENSE

data_dir: ./topics/_table-of-contents

collections:
  web-dev-1:
    output: true
    permalink: /courses/web-dev-1/:path/
    title: "Web Dev 1"
  web-dev-2:
    output: true
    permalink: /courses/web-dev-2/:path/
    title: "Web Dev 2"
  web-dev-3:
    output: true
    permalink: /courses/web-dev-3/:path/
    title: "Web Dev 3"
  web-dev-4:
    output: true
    permalink: /courses/web-dev-4/:path/
    title: "Web Dev 4"
  web-dev-5:
    output: true
    permalink: /courses/web-dev-5/:path/
    title: "Web Dev 5"
  web-dev-6:
    output: true
    permalink: /courses/web-dev-6/:path/
    title: "Web Dev 6"
    disabled: true

kramdown:
  input: GFM

defaults:
  - scope:
      path: "topics"
    values:
      layout: article
  - scope:
      path: ""
      type: "web-dev-1"
    values:
      layout: week
  - scope:
      path: ""
      type: "web-dev-2"
    values:
      layout: week
  - scope:
      path: ""
      type: "web-dev-3"
    values:
      layout: week
  - scope:
      path: ""
      type: "web-dev-4"
    values:
      layout: week
  - scope:
      path: ""
      type: "web-dev-5"
    values:
      layout: week
  - scope:
      path: ""
      type: "web-dev-6"
    values:
      layout: week

########################################
# WEBSITE SPECIFIC CONFIG
########################################

max_weeks: 15

next_week:
  title: "Preview next week"
  submit: "Get a jump on things."
  type: next
  card_class: "card-subtle"
