version: 34

permalink: pretty
highlighter: none

exclude:
  - README.md
  - LICENSE
  - gulpfile.js
  - package.json
  - tmp
  - node_modules
  - css-src
  - js-src
  - images-embed
  - _web-dev-1/README.md
  - _web-dev-1/LICENSE
  - _web-dev-2/README.md
  - _web-dev-2/LICENSE
  - _web-dev-3/README.md
  - _web-dev-3/LICENSE
  - _web-dev-4/README.md
  - _web-dev-4/LICENSE

data_dir: ./topics/_table-of-contents

collections:
  web-dev-1:
    output: true
    permalink: /courses/web-dev-1/:path/
    title: "Web Dev 1"
  web-dev-2:
    output: true
    permalink: /courses/web-dev-2/:path/
    title: "Web Dev 2"
  web-dev-3:
    output: true
    permalink: /courses/web-dev-3/:path/
    title: "Web Dev 3"
  web-dev-4:
    output: true
    permalink: /courses/web-dev-4/:path/
    title: "Web Dev 4"
  web-dev-5:
    title: "Web Dev 5"
    desc: "Graphic designers are hired for their personality and their work quality. The first interaction potential employers have is through the designer’s online presence—most importantly a portfolio website. Leasing personal domains, configuring servers for email addresses, and peer reviews are some of the topics explored to launch a successful personal portfolio website."
  web-dev-6:
    title: "Web Dev 6"
    desc: "No web projects are created by just one person—collaboration with other people is fundamental to successful websites. Teams of students organize and create large-scale websites using project management tools, version control systems, online messaging, and issue trackers."

kramdown:
  input: GFM

defaults:
  - scope:
      path: "topics"
    values:
      layout: article
  - scope:
      path: ""
      type: "web-dev-1"
    values:
      layout: week
  - scope:
      path: ""
      type: "web-dev-2"
    values:
      layout: week
  - scope:
      path: ""
      type: "web-dev-3"
    values:
      layout: week
  - scope:
      path: ""
      type: "web-dev-4"
    values:
      layout: week
  - scope:
      path: ""
      type: "web-dev-5"
    values:
      layout: week
  - scope:
      path: ""
      type: "web-dev-6"
    values:
      layout: week

########################################
# WEBSITE SPECIFIC CONFIG
########################################

max_weeks: 15

next_week:
  title: "Preview next week"
  submit: "Get a jump on things."
  type: next
  card_class: "card--subtle"
