version: 3

data_dir: ./topics/_table-of-contents
permalink: pretty

exclude:
  - README.md
  - LICENSE
  - gulpfile.js
  - package.json
  - .editorconfig
  - .gitignore
  - tmp
  - node_modules
  - css/*.css
  - js/*.js

highlighter: none

kramdown:
  input: GFM

defaults:
  -
    scope:
      path: ""
    values:
      layout: article
