version: 63

permalink: pretty
highlighter: none

exclude:
  - README.md
  - LICENSE
  - gulpfile.js
  - package.json
  - tmp
  - node_modules
  - css-src
  - js-src
  - vendor
  - images-embed
  - _web-dev-1/README.md
  - _web-dev-1/LICENSE
  - _web-dev-2/README.md
  - _web-dev-2/LICENSE
  - _web-dev-3/README.md
  - _web-dev-3/LICENSE
  - _web-dev-4/README.md
  - _web-dev-4/LICENSE
  - _web-dev-5/README.md
  - _web-dev-5/LICENSE
  - _web-dev-6/README.md
  - _web-dev-6/LICENSE

data_dir: ./topics/_table-of-contents

collections:
  web-dev-1:
    output: true
    permalink: /courses/web-dev-1/:path/
    title: "Web Dev 1"
  web-dev-2:
    output: true
    permalink: /courses/web-dev-2/:path/
    title: "Web Dev 2"
  web-dev-3:
    output: true
    permalink: /courses/web-dev-3/:path/
    title: "Web Dev 3"
  web-dev-4:
    output: true
    permalink: /courses/web-dev-4/:path/
    title: "Web Dev 4"
  web-dev-5:
    output: true
    permalink: /courses/web-dev-5/:path/
    title: "Web Dev 5"
  web-dev-6:
    output: true
    permalink: /courses/web-dev-6/:path/
    title: "Web Dev 6"
    disabled: true

kramdown:
  input: GFM

defaults:
  - scope:
      path: "topics"
    values:
      layout: article
  - scope:
      path: ""
      type: "web-dev-1"
    values:
      layout: week
  - scope:
      path: ""
      type: "web-dev-2"
    values:
      layout: week
  - scope:
      path: ""
      type: "web-dev-3"
    values:
      layout: week
  - scope:
      path: ""
      type: "web-dev-4"
    values:
      layout: week
  - scope:
      path: ""
      type: "web-dev-5"
    values:
      layout: week
  - scope:
      path: ""
      type: "web-dev-6"
    values:
      layout: week

########################################
# WEBSITE SPECIFIC CONFIG
########################################

max_weeks: 15

next_week:
  title: "Preview next week"
  submit: "Get a jump on things."
  type: next
  card_class: "card-subtle"

no_activities:
  title: ""
  submit: "No activities or quizzes this week."
  type: activity
  card_class: "card-placeholder"
  no_button: true

no_lessons:
  title: ""
  submit: "No lessons this week."
  type: lesson
  card_class: "card-placeholder"
  no_button: true

no_exercises:
  title: ""
  submit: "No coding exercises this week."
  type: code
  card_class: "card-placeholder"
  no_button: true

vlo:
  - "Conceptualize and develop design solutions using principles of design to create visual communications that meet the needs of the projects."
  - "Employ the design process to create design solutions that meet the project objectives and the needs of the client and/or user."
  - "Plan, create and use photography, illustration and typography in design layouts to meet the requirements of the creative brief."
  - "Design, develop and create a variety of media products using relevant, current and/or emerging technologies."
  - "Communicate ideas, design concepts and opinions clearly and persuasively to others."
  - "Use recognized industry practices throughout the design process and related business tasks."
  - "Plan, implement, and evaluate graphic design projects using project management skills to deliver quality work to clients according to schedule and within budget."
  - "Complete all work in a professional and ethical manner, and in accordance with all applicable legislation and regulations."
  - "Keep current with visual media design trends, technologies and industry practices using strategies that enhance work performance and guide professional development."
  - "Identify and apply discipline-specific practices that contribute to the local and global community through social responsibility, economic commitment and environmental stewardship."

ees:
  - "Communicate clearly, concisely and correctly in the written, spoken and visual form that fulfills the purpose and meets the needs of the audience."
  - "Respond to written, spoken or visual messages in a manner that ensures effective communication."
  - "Execute mathematical operations accurately."
  - "Apply a systematic approach to solve problems."
  - "Use a variety of thinking skills to anticipate and solve problems."
  - "Locate, select, organize and document information using appropriate technology and information systems."
  - "Analyze, evaluate and apply relevant information from a variety of sources."
  - "Show respect for diverse opinions, values, belief systems and contributions of others."
  - "Interact with others in groups or teams in ways that contribute to effective working relationships and the achievement of goals."
  - "Manage the use of time and other resources to complete projects."
  - "Take responsibility for one's own actions, decisions and consequences."
